# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "blob-tfstate7fax4"
    key                  = "./terraform.tfstate"
    resource_group_name  = "tfstate-rg"
    storage_account_name = "tfstate7fax4"
  }
}
