# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "azure-tg-infra"
    key                  = "./terraform.tfstate"
    resource_group_name  = "tfstate-rg"
    storage_account_name = "tfstate7fax4"
  }
}
